import productImage from "../../../../assets/images/products/product-image.webp";

export const FeaturedProductsData = [
  {
    id: 1,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 1",
    ratings: 0.7,
    totalRatings: 48,
    price: 1121.53,
    discount: 51,
  },
  {
    id: 2,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 2",
    ratings: 3.0,
    totalRatings: 375,
    price: 643.73,
    discount: 24,
  },
  {
    id: 3,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 3",
    ratings: 4.6,
    totalRatings: 476,
    price: 379.96,
    discount: 36,
  },
  {
    id: 4,
    image: productImage,
    pCategory: "Audio & Headphones",
    pName: "iPhone 14 Pro Max - 4",
    ratings: 2.3,
    totalRatings: 260,
    price: 822.44,
    discount: 10,
  },
  {
    id: 5,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 5",
    ratings: 2.4,
    totalRatings: 266,
    price: 61.26,
    discount: 42,
  },
  {
    id: 6,
    image: productImage,
    pCategory: "Audio & Headphones",
    pName: "iPhone 14 Pro Max - 6",
    ratings: 4.0,
    totalRatings: 101,
    price: 1370.06,
    discount: 15,
  },
  {
    id: 7,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 7",
    ratings: 3.2,
    totalRatings: 417,
    price: 766.37,
    discount: 5,
  },
  {
    id: 8,
    image: productImage,
    pCategory: "Audio & Headphones",
    pName: "iPhone 14 Pro Max - 8",
    ratings: 0.6,
    totalRatings: 10,
    price: 1193.2,
    discount: 41,
  },
  {
    id: 9,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 9",
    ratings: 3.9,
    totalRatings: 213,
    price: 1342.52,
    discount: 29,
  },
  {
    id: 10,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 10",
    ratings: 0.0,
    totalRatings: 13,
    price: 1377.08,
    discount: 24,
  },
  {
    id: 11,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 11",
    ratings: 3.9,
    totalRatings: 49,
    price: 469.2,
    discount: 50,
  },
  {
    id: 12,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 12",
    ratings: 0.9,
    totalRatings: 347,
    price: 1176.42,
    discount: 24,
  },
  {
    id: 13,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 13",
    ratings: 1.7,
    totalRatings: 383,
    price: 641.8,
    discount: 44,
  },
  {
    id: 14,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 14",
    ratings: 2.3,
    totalRatings: 240,
    price: 346.09,
    discount: 31,
  },
  {
    id: 15,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 15",
    ratings: 1.0,
    totalRatings: 334,
    price: 937.89,
    discount: 35,
  },
  {
    id: 16,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 16",
    ratings: 1.7,
    totalRatings: 275,
    price: 856.64,
    discount: 46,
  },
  {
    id: 17,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 17",
    ratings: 0.3,
    totalRatings: 20,
    price: 337.16,
    discount: 38,
  },
  {
    id: 18,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 18",
    ratings: 0.7,
    totalRatings: 136,
    price: 1290.5,
    discount: 30,
  },
  {
    id: 19,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 19",
    ratings: 1.9,
    totalRatings: 266,
    price: 660.4,
    discount: 59,
  },
  {
    id: 20,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 20",
    ratings: 1.9,
    totalRatings: 94,
    price: 239.78,
    discount: 37,
  },
  {
    id: 21,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 21",
    ratings: 0.0,
    totalRatings: 444,
    price: 788.54,
    discount: 31,
  },
  {
    id: 22,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 22",
    ratings: 1.6,
    totalRatings: 450,
    price: 1297.22,
    discount: 14,
  },
  {
    id: 23,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 23",
    ratings: 0.3,
    totalRatings: 350,
    price: 885.93,
    discount: 28,
  },
  {
    id: 24,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 24",
    ratings: 2.5,
    totalRatings: 416,
    price: 554.89,
    discount: 8,
  },
  {
    id: 25,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 25",
    ratings: 0.9,
    totalRatings: 43,
    price: 62.7,
    discount: 23,
  },
  {
    id: 26,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 26",
    ratings: 3.8,
    totalRatings: 479,
    price: 694.86,
    discount: 23,
  },
  {
    id: 27,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 27",
    ratings: 2.5,
    totalRatings: 471,
    price: 487.28,
    discount: 50,
  },
  {
    id: 28,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 28",
    ratings: 2.3,
    totalRatings: 48,
    price: 1198.0,
    discount: 15,
  },
  {
    id: 29,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 29",
    ratings: 0.9,
    totalRatings: 367,
    price: 637.89,
    discount: 56,
  },
  {
    id: 30,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 30",
    ratings: 1.2,
    totalRatings: 432,
    price: 1362.21,
    discount: 10,
  },
  {
    id: 31,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 31",
    ratings: 4.0,
    totalRatings: 37,
    price: 433.66,
    discount: 25,
  },
  {
    id: 32,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 32",
    ratings: 0.7,
    totalRatings: 267,
    price: 339.44,
    discount: 51,
  },
  {
    id: 33,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 33",
    ratings: 4.6,
    totalRatings: 167,
    price: 1437.52,
    discount: 15,
  },
  {
    id: 34,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 34",
    ratings: 4.0,
    totalRatings: 472,
    price: 1322.1,
    discount: 14,
  },
  {
    id: 35,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 35",
    ratings: 2.9,
    totalRatings: 44,
    price: 477.8,
    discount: 41,
  },
  {
    id: 36,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 36",
    ratings: 2.5,
    totalRatings: 245,
    price: 630.03,
    discount: 27,
  },
  {
    id: 37,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 37",
    ratings: 2.1,
    totalRatings: 437,
    price: 1321.16,
    discount: 13,
  },
  {
    id: 38,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 38",
    ratings: 1.9,
    totalRatings: 50,
    price: 1446.68,
    discount: 35,
  },
  {
    id: 39,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 39",
    ratings: 4.6,
    totalRatings: 43,
    price: 1458.53,
    discount: 19,
  },
  {
    id: 40,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 40",
    ratings: 4.7,
    totalRatings: 411,
    price: 1206.74,
    discount: 42,
  },
  {
    id: 41,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 41",
    ratings: 1.2,
    totalRatings: 271,
    price: 1494.26,
    discount: 6,
  },
  {
    id: 42,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 42",
    ratings: 2.8,
    totalRatings: 400,
    price: 475.94,
    discount: 48,
  },
  {
    id: 43,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 43",
    ratings: 3.3,
    totalRatings: 154,
    price: 168.88,
    discount: 34,
  },
  {
    id: 44,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 44",
    ratings: 1.1,
    totalRatings: 314,
    price: 1057.22,
    discount: 50,
  },
  {
    id: 45,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 45",
    ratings: 1.6,
    totalRatings: 87,
    price: 684.81,
    discount: 38,
  },
  {
    id: 46,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 46",
    ratings: 4.8,
    totalRatings: 337,
    price: 1036.5,
    discount: 13,
  },
  {
    id: 47,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 47",
    ratings: 4.3,
    totalRatings: 56,
    price: 966.42,
    discount: 53,
  },
  {
    id: 48,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 48",
    ratings: 2.2,
    totalRatings: 301,
    price: 610.64,
    discount: 42,
  },
  {
    id: 49,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 49",
    ratings: 4.9,
    totalRatings: 67,
    price: 426.55,
    discount: 39,
  },
  {
    id: 50,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 50",
    ratings: 1.7,
    totalRatings: 484,
    price: 224.29,
    discount: 19,
  },
  {
    id: 51,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 51",
    ratings: 3.6,
    totalRatings: 18,
    price: 1044.28,
    discount: 18,
  },
  {
    id: 52,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 52",
    ratings: 1.6,
    totalRatings: 419,
    price: 816.97,
    discount: 6,
  },
  {
    id: 53,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 53",
    ratings: 0.9,
    totalRatings: 387,
    price: 1429.0,
    discount: 35,
  },
  {
    id: 54,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 54",
    ratings: 2.2,
    totalRatings: 312,
    price: 1076.95,
    discount: 12,
  },
  {
    id: 55,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 55",
    ratings: 0.4,
    totalRatings: 165,
    price: 170.61,
    discount: 31,
  },
  {
    id: 56,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 56",
    ratings: 0.6,
    totalRatings: 311,
    price: 82.53,
    discount: 7,
  },
  {
    id: 57,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 57",
    ratings: 1.5,
    totalRatings: 155,
    price: 1260.48,
    discount: 36,
  },
  {
    id: 58,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 58",
    ratings: 2.5,
    totalRatings: 290,
    price: 1150.13,
    discount: 18,
  },
  {
    id: 59,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 59",
    ratings: 3.8,
    totalRatings: 372,
    price: 400.09,
    discount: 39,
  },
  {
    id: 60,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 60",
    ratings: 0.7,
    totalRatings: 183,
    price: 222.32,
    discount: 26,
  },
  {
    id: 61,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 61",
    ratings: 4.8,
    totalRatings: 25,
    price: 757.06,
    discount: 32,
  },
  {
    id: 62,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 62",
    ratings: 4.1,
    totalRatings: 484,
    price: 47.91,
    discount: 54,
  },
  {
    id: 63,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 63",
    ratings: 3.1,
    totalRatings: 279,
    price: 1138.79,
    discount: 46,
  },
  {
    id: 64,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 64",
    ratings: 0.0,
    totalRatings: 195,
    price: 1316.16,
    discount: 55,
  },
  {
    id: 65,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 65",
    ratings: 3.0,
    totalRatings: 219,
    price: 574.51,
    discount: 19,
  },
  {
    id: 66,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 66",
    ratings: 4.3,
    totalRatings: 114,
    price: 39.94,
    discount: 17,
  },
  {
    id: 67,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 67",
    ratings: 1.0,
    totalRatings: 154,
    price: 1465.21,
    discount: 44,
  },
  {
    id: 68,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 68",
    ratings: 4.7,
    totalRatings: 402,
    price: 1051.28,
    discount: 46,
  },
  {
    id: 69,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 69",
    ratings: 2.4,
    totalRatings: 173,
    price: 608.63,
    discount: 53,
  },
  {
    id: 70,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 70",
    ratings: 2.5,
    totalRatings: 239,
    price: 275.03,
    discount: 12,
  },
  {
    id: 71,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 71",
    ratings: 3.9,
    totalRatings: 386,
    price: 361.88,
    discount: 32,
  },
  {
    id: 72,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 72",
    ratings: 1.9,
    totalRatings: 176,
    price: 357.86,
    discount: 56,
  },
  {
    id: 73,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 73",
    ratings: 3.7,
    totalRatings: 438,
    price: 1212.6,
    discount: null,
  },
  {
    id: 74,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 74",
    ratings: 4.7,
    totalRatings: 204,
    price: 571.9,
    discount: 45,
  },
  {
    id: 75,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 75",
    ratings: 0.5,
    totalRatings: 434,
    price: 401.55,
    discount: 12,
  },
  {
    id: 76,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 76",
    ratings: 0.1,
    totalRatings: 388,
    price: 636.89,
    discount: 12,
  },
  {
    id: 77,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 77",
    ratings: 0.8,
    totalRatings: 471,
    price: 1033.88,
    discount: 35,
  },
  {
    id: 78,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 78",
    ratings: 3.2,
    totalRatings: 303,
    price: 329.28,
    discount: 27,
  },
  {
    id: 79,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 79",
    ratings: 1.3,
    totalRatings: 405,
    price: 1066.73,
    discount: 30,
  },
  {
    id: 80,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 80",
    ratings: 3.9,
    totalRatings: 187,
    price: 1026.0,
    discount: 41,
  },
  {
    id: 81,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 81",
    ratings: 2.7,
    totalRatings: 297,
    price: 850.75,
    discount: 8,
  },
  {
    id: 82,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 82",
    ratings: 3.0,
    totalRatings: 22,
    price: 24.11,
    discount: 19,
  },
  {
    id: 83,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 83",
    ratings: 3.2,
    totalRatings: 130,
    price: 1384.44,
    discount: 36,
  },
  {
    id: 84,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 84",
    ratings: 4.2,
    totalRatings: 29,
    price: 789.54,
    discount: 15,
  },
  {
    id: 85,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 85",
    ratings: 4.4,
    totalRatings: 492,
    price: 201.56,
    discount: 21,
  },
  {
    id: 86,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 86",
    ratings: 1.6,
    totalRatings: 324,
    price: 985.83,
    discount: 24,
  },
  {
    id: 87,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 87",
    ratings: 4.4,
    totalRatings: 413,
    price: 383.56,
    discount: 49,
  },
  {
    id: 88,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 88",
    ratings: 2.5,
    totalRatings: 280,
    price: 1127.07,
    discount: 15,
  },
  {
    id: 89,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 89",
    ratings: 4.6,
    totalRatings: 439,
    price: 1106.12,
    discount: 48,
  },
  {
    id: 90,
    image: productImage,
    pCategory: "Mobile & Accessories",
    pName: "iPhone 14 Pro Max - 90",
    ratings: 4.1,
    totalRatings: 465,
    price: 151.51,
    discount: 24,
  },
  {
    id: 91,
    image: productImage,
    pCategory: "Mobile & Accessories",
    pName: "iPhone 14 Pro Max - 91",
    ratings: 3.2,
    totalRatings: 396,
    price: 1178.24,
    discount: 44,
  },
  {
    id: 92,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 92",
    ratings: 2.1,
    totalRatings: 228,
    price: 506.85,
    discount: 21,
  },
  {
    id: 93,
    image: productImage,
    pCategory: "Mobile & Accessories",
    pName: "iPhone 14 Pro Max - 93",
    ratings: 1.7,
    totalRatings: 122,
    price: 333.66,
    discount: 15,
  },
  {
    id: 94,
    image: productImage,
    pCategory: "Mobile & Accessories",
    pName: "iPhone 14 Pro Max - 94",
    ratings: 2.3,
    totalRatings: 253,
    price: 1164.28,
    discount: 14,
  },
  {
    id: 95,
    image: productImage,
    pCategory: "Mobile & Accessories",
    pName: "iPhone 14 Pro Max - 95",
    ratings: 2.9,
    totalRatings: 99,
    price: 142.52,
    discount: 13,
  },
  {
    id: 96,
    image: productImage,
    pCategory: "Mobile & Accessories",
    pName: "iPhone 14 Pro Max - 96",
    ratings: 2.8,
    totalRatings: 83,
    price: 523.54,
    discount: 5,
  },
  {
    id: 97,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 97",
    ratings: 1.5,
    totalRatings: 452,
    price: 915.62,
    discount: 55,
  },
  {
    id: 98,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 98",
    ratings: 0.6,
    totalRatings: 296,
    price: 1437.26,
    discount: 24,
  },
  {
    id: 99,
    image: productImage,
    pCategory: "Mobile & Accessories",
    pName: "iPhone 14 Pro Max - 99",
    ratings: 4.3,
    totalRatings: 311,
    price: 651.38,
    discount: 32,
  },
  {
    id: 100,
    image: productImage,
    pCategory: "Mobile & Accessories",
    pName: "iPhone 14 Pro Max - 100",
    ratings: 1.2,
    totalRatings: 141,
    price: 856.52,
    discount: 35,
  },
];
