import productImage from "../../../../assets/images/products/product-image.webp";
export const SpringSaleData = [
  {
    id: 1,
    image: productImage,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 1",
    ratings: 0.7,
    totalRatings: 48,
    price: 1121.53,
    discount: 51,
    stock: 1500,
    sold: 100,
  },
  {
    id: 2,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 2",
    ratings: 3.0,
    totalRatings: 375,
    price: 643.73,
    discount: 24,
    stock: 1000,
    sold: 982,
  },
  {
    id: 3,
    image: productImage,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 3",
    ratings: 4.6,
    totalRatings: 476,
    price: 379.96,
    discount: 36,
    stock: 100,
    sold: 90,
  },
  {
    id: 4,
    image: productImage,
    pCategory: "Audio & Headphones",
    pName: "iPhone 14 Pro Max - 4",
    ratings: 2.3,
    totalRatings: 260,
    price: 822.44,
    discount: 10,
    stock: 200,
    sold: 189,
  },
];
